### ISSUE TITLE
Safariでログイン時にユーザー名の補完ができない

### ISSUE THREAD

**Issue by polyomino-24** [yosupo06/library-checker-frontend#10]
chromeとかだとうまくいってると思うんですが、safariだとユーザー名だけ補完できなくて少し不便なので、ログインの部分のname属性をusernameに変更していただけるとありがたいです。面倒だったら無視してください。

**Comment by yosupo06** [comment]
https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element ここを参考に、autocomplete="username"付けてみました ダメそうだったら再openお願いします
