### ISSUE TITLE
ブラウザバックした時に問題のカテゴリを選んでいた状態を保存しておらず、意図しない場所が表示されてしまう。

### ISSUE THREAD

**Issue by catupper** [yosupo06/library-checker-frontend#123]
## 概要
問題一覧ページで問題カテゴリを選んでから問題ページに遷移した後、ブラウザバックで戻ると、いままで違う場所にJumpしてしまいます。

## 再現
- 問題一覧ページを開く
- TabでMathカテゴリを選ぶ
- ややスクロールダウンして問題Sqrt Modなどを選択して問題ページにジャンプする
- ブラウザバックする
- ページトップでもなく、先ほどとも違う場所が表示される。

## 原因
ブラウザバックしたときに、どこまでスクロールしていたかは再現してくれるが、カテゴリの絞り込みは再現されないのでAllの状態である位置にスクロールしたところに戻ってくる。

## 解決策
カテゴリを選んだときに問題を絞り込むのではなく、ハッシュを用いて、その位置までスクロールしてくれる仕様にするのはどうか。

**Comment by catupper** [comment]
こんなイメージというのを作ってみました
もっとこうした方が良いという意見あれば歓迎です

https://github.com/yosupo06/library-checker-frontend/pull/124

**Comment by yosupo06** [comment]
次の2つの理由から、しっかりfilterして欲しい派です

- たとえばMathをクリックしたあとにトップのバー(submission, ranking, etc)にアクセスしたいときに、大量に上スクロールをするかAllをクリック(=非自明な操作)する必要がある
- 特定のジャンルの問題を解いていく(通称XX埋め)人は、全部緑色になったページを見て悦に浸りたい気がする

まだ試せていないのですが、　

- https://stackoverflow.com/questions/47495696/react-router-how-to-restore-state-after-browser-back-button これを見るにProblems.tsxのselectedIdxをhistory.stateに入れる
- history.scrollRestorationを使ってでブラウザにスクロール位置の復元をやめるよう要求する https://developer.mozilla.org/ja/docs/Web/API/History/scrollRestoration

あたりで解決できるかもなと思っています

**Comment by catupper** [comment]
しっかりfilterしたい旨理解しました。
では、
- ブラウザバックしたときに、かつて絞り込んでいたのと同じ絞り込みがなされているようにする
- スクロール位置は復元してもらう

というアプローチを取ろうと思います。よいでしょうか？
