### ISSUE TITLE
メモリ量が見にくい

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-frontend#3]
byte数はダメ、適切にX KBとかY MBとか

**Comment by hos-lyric** [comment]
M が 1000000 か 1024000 か 1048576 か，みたいなのがどこか人が読めるところに書いてあるとハッピー

**Comment by yosupo06** [comment]
- 紛れがないようにMBではなくMiBを採用
- 実装がめんどくさいから使い分けとかやめて全部MiB 要望がきたら再検討
