### ISSUE TITLE
ランキング機能

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-frontend#36]
ほしくないですか？ これがあると Library Checker 埋めに嵌まる人が増え、開発や問題追加に貢献してくれる人も増えます。
カテゴリ (Data Structure, Math, …) ごとにあるとなおよさそう (1位を取れる機会の数は多いほどよいので)

**Comment by yosupo06** [comment]
あると良さそうわかる

**Comment by yosupo06** [comment]
付けました　カテゴリの情報が今全くデータベースにないので、後者はもうちょっと変更しないと厳しそう

**Comment by yosupo06** [comment]
AC数が目視と違う　一体何が起きてしまっているんだ？

**Comment by yosupo06** [comment]
なんでもいいから提出した問題の種類数になってた
