### ISSUE TITLE
My Submissions 画面のページングのリンクが正しくない

### ISSUE THREAD

**Issue by emkjp** [yosupo06/library-checker-frontend#38]
例えば、
https://judge.yosupo.jp/submissions?user=emkjp
の ２ページ目へのリンクが
https://judge.yosupo.jp/submissions?page=2
になっていますが、
https://judge.yosupo.jp/submissions?page=2&user=emkjp
が適切だと思います。

**Comment by yosupo06** [comment]
わ、本当です　ありがとうございます

**Comment by yosupo06** [comment]
直しました
