### ISSUE TITLE
API

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-frontend#42]
https://twitter.com/___n___z/status/1257932857504399360?s=20

熱烈スクレイピングをしてもいいが https://github.com/kenkoooo/AtCoderProblems/ のUserInfo APIみたいなのがあるとうれしい

**Comment by yosupo06** [comment]
gRPCなら既にタグがある(or Web gRPCならすぐに足せる気がする)んですが、それでは不十分？

**Comment by yosupo06** [comment]
よく考えたらUserInfo系のAPIなかった気がします

**Comment by yosupo06** [comment]
- API: Rankingページで使ってるAPI(https://github.com/yosupo06/library-checker-judge/blob/master/api/proto/library_checker.proto の Ranking)があり、これが用途にあってそう
- REST API: 今のところ提供する気はないです、なぜなら内部で使う予定がないからです。これを提供すると様々な外部サービスが…！という場合は考慮の余地がありますが
- web gRPC: 提供してもいいです　将来的にフロントエンドをreactなどで置き換えるとしたら使いそうで、遅かれ早かれなので　しかしながらhtmlにちょっとjavascript書いてアクセス、みたいな用途(多分rating-historyはこれ？)ではめんどくさいです

**Comment by beet-aizu** [comment]
ありがとうございます　最初のやつを試してみます

**Comment by yosupo06** [comment]
gRPC-Webを立てました。以下の手順で使えると思います(htmlにちょっとjsを書き込んでいい感じに使いたい、という用途を想定します)。

## ディレクトリ構成

```
- library-checker-judge/
  - api/
    - proto/
      - library_checker.proto
- beet/
```
このようなディレクトリ構成で、beetフォルダの中で作業するものとします(library-checker-judgeはクローンしてください)

##  protoファイルをjsファイルに変換する

```
protoc -I ../library-checker-judge/api/proto/ ../library-checker-judge/api/proto/library_checker.proto \
    --js_out=import_style=commonjs:. \
    --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./
```

を実行してください。gRPC関連の諸々のインストールが必要になります macなら多分以下です

```
brew install protoc-gen-go protoc-gen-grpc-web
```

実行すると`library_checker_grpc_web_pb.js`, `library_checker_pb.js`が`beet`ディレクトリの下に出来ているはずです。

## jsファイルを使える(?)jsファイルに変換する

`beet/main.js`として以下のように記述します

```
const { LibraryCheckerServiceClient } = require('./library_checker_grpc_web_pb');
const { RankingRequest } = require('./library_checker_pb');

let client = new LibraryCheckerServiceClient('https://grpcweb-apiv1.yosupo.jp:443');

client.ranking(new RankingRequest(), {}, (err, response) => {
    if (err) {
        console.log(err.code);
        console.log(err.message);
    } else {
        console.log(response.getStatisticsList());
    }
});
```

また、`beet/package.json`として以下を置きます

```
{
  "devDependencies": {
    "@grpc/proto-loader": "^0.3.0",
    "google-protobuf": "^3.6.1",
    "grpc": "^1.15.0",
    "grpc-web": "^1.0.0",
    "webpack": "^4.16.5",
    "webpack-cli": "^3.1.0"
  }
}
```

そして、`npm install`を実行します。大量のログ出力と時間がかかります。明らかにC++をコンパイルしてそうなログが出てくるんですが何故なのかは謎です。

そして`npx webpack main.js`を実行します。全てがうまくいくと`dist/main.js`が出来ているはずで、このjsファイルはいい感じに使えます。

## htmlに入れる

これはやるだけです、例えば`beet/index.html`として次を置いて、ブラウザで開きます。

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <script src="./dist/main.js"></script>
</head>

<body>
    <p>Hello world</p>
</body>

</html>
```

うまくいくとコンソールに巨大な配列が出力されているはずです。chromeなら中身がポチポチ見れて、yosupo judgeのランキングを配列にしたものが格納されているはずです。

**Comment by beet-aizu** [comment]
できました！ありがとうございます！
