### ISSUE TITLE
Time順にソートしたあとページを遷移するとソート が解除される

### ISSUE THREAD

**Issue by sansen0796** [yosupo06/library-checker-frontend#44]
例として
https://judge.yosupo.jp/submissions?problem=convolution_mod&user=&status=AC&order=%2Btime
から2ページ目へ行こうとするとソート が解除されて
https://judge.yosupo.jp/submissions?page=2&problem=convolution_mod&status=AC
に移ります
でもできれば以下のページに移って欲しいなと思ってます
https://judge.yosupo.jp/submissions?page=2&problem=convolution_mod&status=AC&order=%2Btime

**Comment by yosupo06** [comment]
ありがとうございます！多分シンプルにバグです
