### ISSUE TITLE
Submission Listのfilterに言語を足したい

### ISSUE THREAD

**Issue by Yang-33** [yosupo06/library-checker-frontend#47]
C++以外の言語の最速コードを探したいのですが、実行速度順にソートするとC++で埋め尽くされていて少し探すのが大変です。
やってみても良いですか？
library-checker-judgeを書き足してからfrontendを書き足せば良いのかなと思っています！

**Comment by yosupo06** [comment]
ありがとうございます！　大まかな流れとしては

1. library-checker-judge/apiでAPIを変更する
  - のSubmissionListに言語filterを足す
  - protoファイルを書き換える
2. frontendをいい感じに変える

で動くと思います！library-checker-problems以外のドキュメント整備具合がかなりひどいんですが

- APIサーバーはdocker-compose叩くだけ
- frontendもgoがインストールされていればやるだけ
- ジャッジサーバー動かすのは至難の業

と言った状態です！(ジャッジサーバーはサンドボックスとか作っているので手元で動かすのが原理上かなり難しく、現状CIのテスト任せになっています…)

**Comment by Yang-33** [comment]
丁寧にありがとうございます！
judgeもfrontendも分かりやすくて、書いてある通りに従えば簡単に動かせました。
時間があるときにやってみます！
