### ISSUE TITLE
ライブラリの URL を登録できない

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-frontend#81]
<https://kmyk.github.io/competitive-programming-library/> と入力して `Change` ボタンを押すと `Key: 'NewUserInfo.LibraryURL' Error:Field validation for 'LibraryURL' failed on the 'lt' tag` というエラーが返ってきます。ライブラリが Unregistered のまま変化しません。

![Screenshot from 2021-03-20 03-09-31](https://user-images.githubusercontent.com/2203128/111824738-ed219e80-8929-11eb-9e16-cbc223cf9302.png)

**Comment by kmyk** [comment]
https://github.com/yosupo06/library-checker-judge/issues/160 で解決して、登録できました。ありがとう

**Comment by yosupo06** [comment]
報告ありがとうございます！
