### ISSUE TITLE
"Library Checker" か "Library-Checker" かの表記を統一してほしい

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-frontend#84]
揺れてるとどっちが正なのか分からなくて言及する際に迷いがちなので

**Comment by yosupo06** [comment]
(表記が揺れていることからわかるように)特に何も決めていませんでした、"Library Checker"が正式名称ということにしておきます。"Library-Checker"は気づいたら直していきます。一応私のスタンスとしては"Library Checker"でも"Library-Checker"でも"librarychecker"でも好きに呼んでくださいという感じです
